title: CS184 Final Project
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

compress_html:
  blanklines: true

latex: "mathjax"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
